server:
  port: 8080
  error:
    whitelabel:
      enabled: false
  shutdown: graceful
  compression:
    enabled: true
  forward-headers-strategy: native

spring:
  application:
    name: productSample

  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:testdb
      username: sa
      password:
      maximum-pool-size: 10
      connection-timeout: 3000
      connection-init-sql: SELECT 1
      minimum-idle: 2
      idle-timeout: 100000
      max-lifetime: 300000

  sql:
    init:
      schema-locations: classpath:database/schema.sql
      data-locations: classpath:database/data.sql
      mode: ALWAYS

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
        show_sql: false
    open-in-view: false
